import { describe, expect, it } from 'vitest';
import { autoFinishSteps, capacity, deck, move, movableRun, newGame, SUITS, undo } from './engine';
describe('FreeCell engine', () => {
  it('creates complete deterministic 7/6-card deals', () => { const a = newGame('42'); expect(deck()).toHaveLength(52); expect(new Set(a.cascades.flat().map((c) => c.id)).size).toBe(52); expect(a.cascades.map((c) => c.length)).toEqual([7,7,7,7,6,6,6,6]); expect(a).toEqual(newGame('42')); expect(a).not.toEqual(newGame('43')); });
  it('moves single cards to cells and undoes', () => { const game = newGame('cell'); const next = move(game, { kind:'cascade', index:0, cardIndex:6 }, { kind:'cell', index:0 })!; expect(next.cells[0]).toBeTruthy(); expect(next.moves).toBe(1); expect(undo(next).cascades).toEqual(game.cascades); });
  it('enforces alternating runs, foundations and supermove capacity', () => { const game = newGame('rules'); expect(movableRun([{id:'a',suit:'clubs',rank:5,color:'black'},{id:'b',suit:'hearts',rank:4,color:'red'}],0)).toBe(true); expect(capacity(game,0)).toBe(5); const ace={id:'hearts-1',suit:'hearts' as const,rank:1,color:'red' as const}; const custom={...game,cascades:[[ace],...game.cascades.slice(1)]}; expect(move(custom,{kind:'cascade',index:0,cardIndex:0},{kind:'foundation',suit:'hearts'})?.foundations.hearts).toEqual([ace]); });
  it('allows a foundation top card back into play', () => { const game=newGame('return'); const ace={id:'hearts-1',suit:'hearts' as const,rank:1,color:'red' as const}; const two={id:'clubs-2',suit:'clubs' as const,rank:2,color:'black' as const}; const custom={...game,cascades:[[two],...game.cascades.slice(1)],foundations:{...game.foundations,hearts:[ace]}}; const returned=move(custom,{kind:'foundation',suit:'hearts'},{kind:'cascade',index:0})!; expect(returned.foundations.hearts).toEqual([]); expect(returned.cascades[0].at(-1)).toEqual(ace); });
  it('auto-finishes only when every remaining card can go directly home', () => { const game=newGame('finish'); const cards=deck(); const foundations=Object.fromEntries(SUITS.map((suit)=>[suit,cards.filter((card)=>card.suit===suit&&card.rank<13)])) as typeof game.foundations; const kings=SUITS.map((suit)=>cards.find((card)=>card.suit===suit&&card.rank===13)!); const ready={...game,cascades:kings.map((card)=>[card]).concat([[],[],[],[]]),cells:[null,null,null,null],foundations}; expect(autoFinishSteps(ready)).toHaveLength(4); expect(autoFinishSteps(newGame('blocked'))).toBeNull(); });
});
