import { useEffect, useRef, useState } from 'react';
import FullscreenButton from '../../shared/FullscreenButton';
import { autoFinishSteps, move, newGame, rankLabel, suitMark, SUITS, undo, won, type Destination, type FreeCellGame, type Source } from './engine';
const KEY = 'servitium.ludus.freecell.v1';
const load = (): FreeCellGame | null => { try { const value = JSON.parse(localStorage.getItem(KEY) ?? 'null'); return value?.version === 1 ? value : null; } catch { return null; } };
const cardName = (card: { rank:number; suit:keyof typeof suitMark }) => `${rankLabel(card.rank)} of ${card.suit}`;
export default function FreeCell({ onBack }: { onBack: () => void }) {
  const [game, setGame] = useState<FreeCellGame>(() => load() ?? newGame(String(Date.now()))); const [selected, setSelected] = useState<Source | null>(null); const [message, setMessage] = useState(''); const [help, setHelp] = useState(false); const [peeked, setPeeked] = useState<string | null>(null);
  const peekTimer = useRef<ReturnType<typeof setTimeout> | null>(null); const suppressPeekClick = useRef(false); const autoTimers = useRef<ReturnType<typeof setTimeout>[]>([]); const autoRunning = useRef(false); const [autoFinishing,setAutoFinishing]=useState(false);
  useEffect(() => { localStorage.setItem(KEY, JSON.stringify(game)); }, [game]);
  useEffect(() => { if (won(game)) return; const id=setInterval(()=>setGame((value)=>({...value,elapsedMs:value.elapsedMs+1000})),1000); return()=>clearInterval(id); }, [won(game)]);
  useEffect(()=>()=>autoTimers.current.forEach(clearTimeout),[]);
  useEffect(()=>{if(autoRunning.current||won(game)||selected)return;const steps=autoFinishSteps(game);if(!steps?.length)return;autoRunning.current=true;setAutoFinishing(true);setMessage('The table can finish cleanly. Moving cards home.');steps.forEach((step,index)=>{autoTimers.current.push(setTimeout(()=>{setGame(step);if(index===steps.length-1){autoRunning.current=false;setAutoFinishing(false);}},180*(index+1)));});},[game.moves,selected]);
  const sourceKey = (source: Source) => source.kind === 'foundation' ? `${source.kind}:${source.suit}` : source.kind === 'cell' ? `${source.kind}:${source.index}` : `${source.kind}:${source.index}:${source.cardIndex}`;
  const sameSource = (source: Source) => Boolean(selected && sourceKey(selected) === sourceKey(source));
  const chooseSource = (source: Source) => { if (sameSource(source)) { setSelected(null); setMessage('Selection cleared.'); return; } setSelected(source); setMessage('Card selected. Choose a destination.'); };
  const place = (destination: Destination) => { if (!selected) return; const next=move(game,selected,destination); if (!next) { setMessage('That move is not allowed.'); return; } setGame(next); setSelected(null); setMessage(won(next)?'FreeCell solved!':'Card moved.'); };
  const fresh = () => { if (game.moves && !confirm('Start a new deal? Current progress will be replaced.')) return; setGame(newGame(crypto.randomUUID())); setSelected(null); };
  const restart = () => { if (game.moves && !confirm('Restart this exact deal?')) return; setGame(newGame(game.deal)); setSelected(null); };
  const quickCell = (source: Source) => { const index=game.cells.findIndex((card)=>!card); if(index<0){setMessage('No free cell is available.');return;} const next=move(game,source,{kind:'cell',index}); if(next){setGame(next);setSelected(null);setMessage('Card moved to a free cell.');}else setMessage('Only one exposed card can move to a free cell.'); };
  const quickFoundation = (source: Source, suit: keyof typeof suitMark) => { const next=move(game,source,{kind:'foundation',suit}); if(next){setGame(next);setSelected(null);setMessage('Card moved to its foundation.');}else setMessage('That card cannot move to its foundation yet.'); };
  const beginPeek = (event: React.PointerEvent, cardId: string) => { if(event.pointerType!=='touch')return; setPeeked(null); peekTimer.current=setTimeout(()=>{setPeeked(cardId);suppressPeekClick.current=true;setMessage('Card revealed. Tap elsewhere to close.');},500); };
  const endPeek = () => { if(peekTimer.current)clearTimeout(peekTimer.current);peekTimer.current=null; };
  return <main className={`freecell-page${autoFinishing?' auto-finishing':''}`}><header className="freecell-bar"><button className="text-button" onClick={onBack}>← Ludus</button><div><b>FreeCell</b><small>Deal {game.deal.slice(0,8)} · {game.moves} moves · {Math.floor(game.elapsedMs/60000)}:{String(Math.floor(game.elapsedMs/1000)%60).padStart(2,'0')}</small></div><FullscreenButton iconOnly /></header>
    {help&&<section className="freecell-help"><b>Build foundations Ace to King by suit.</b> Cascades descend in alternating colours. Use the four free cells and empty columns to rearrange cards. Select a card or ordered run, then select its destination.</section>}
    <section className="freecell-top" aria-label="Free cells and foundations"><div className="freecell-spots">{game.cells.map((card,index)=>{const source:Source={kind:'cell',index};return <button key={index} className={`card-slot ${sameSource(source)?'selected':''}`} aria-pressed={sameSource(source)} aria-label={card?`Free cell ${index+1}, ${cardName(card)}`:`Empty free cell ${index+1}`} onDoubleClick={()=>card&&quickFoundation(source,card.suit)} onClick={()=>card?chooseSource(source):place({kind:'cell',index})}>{card&&<CardFace card={card}/>}</button>})}</div><div className="freecell-spots">{SUITS.map((suit)=>{const card=game.foundations[suit].at(-1);const source:Source={kind:'foundation',suit};return <button key={suit} className={`card-slot foundation ${sameSource(source)?'selected':''}`} aria-pressed={sameSource(source)} aria-label={`${suit} foundation, ${card?rankLabel(card.rank):'empty'}`} onClick={()=>card&&(!selected||selected.kind==='foundation')?chooseSource(source):place({kind:'foundation',suit})}>{card?<CardFace card={card}/>:suitMark[suit]}</button>})}</div></section>
    <section className="cascades" aria-label="FreeCell tableau" onPointerDown={(event)=>{if(event.target===event.currentTarget)setPeeked(null)}}>{game.cascades.map((column,index)=><div className="cascade" key={index}><button className="cascade-target" aria-label={`Cascade ${index+1}${column.length?', destination':' empty'}`} onClick={()=>selected?.kind==='cascade'&&selected.index===index?setSelected(null):place({kind:'cascade',index})}/>{column.map((card,cardIndex)=>{const source:Source={kind:'cascade',index,cardIndex};return <button key={card.id} className={`playing-card ${selected?.kind==='cascade'&&selected.index===index&&cardIndex>=selected.cardIndex?'selected':''}${peeked===card.id?' peek':''}`} style={{top:`${cardIndex*clampOffset(column.length)}px`}} aria-label={`${cardName(card)}, cascade ${index+1}`} aria-pressed={sameSource(source)} onPointerDown={(event)=>beginPeek(event,card.id)} onPointerUp={endPeek} onPointerCancel={endPeek} onDoubleClick={(event)=>{event.stopPropagation();quickCell(source);}} onClick={(event)=>{event.stopPropagation();if(suppressPeekClick.current){suppressPeekClick.current=false;return;}setPeeked(null);if(selected?.kind==='cascade'&&selected.index===index)chooseSource(source);else if(selected)place({kind:'cascade',index});else chooseSource(source);}}><CardFace card={card}/></button>})}</div>)}</section>
    <nav className="game-controls freecell-controls" aria-label="FreeCell controls"><button onClick={()=>{setGame(undo(game));setSelected(null);}} disabled={!game.history.length}><span>↶</span><small>Undo</small></button><button onClick={restart}><span>↺</span><small>Restart</small></button><button onClick={()=>setHelp(!help)}><span>?</span><small>Help</small></button><button onClick={fresh}><span>＋</span><small>New</small></button></nav>
    <div className="sr-only" aria-live="polite">{message}</div>{won(game)&&<div className="freecell-win"><div className="confetti" aria-hidden="true">{Array.from({length:32},(_,index)=><i key={index}/>)}</div><h1>Deal solved</h1><p>{game.moves} moves</p><button className="primary" onClick={fresh}>New deal</button></div>}
  </main>;
}
const clampOffset=(length:number)=>Math.max(22,Math.min(34,360/Math.max(1,length)));
function CardFace({card}:{card:{rank:number;suit:keyof typeof suitMark;color:'red'|'black'}}){return <span className={card.color} data-mark={suitMark[card.suit]}><b>{rankLabel(card.rank)}</b><i>{suitMark[card.suit]}</i></span>;}
