import { useEffect, useState } from 'react';
import FullscreenButton from '../../shared/FullscreenButton';
import { move, newGame, rankLabel, suitMark, SUITS, undo, won, type Destination, type FreeCellGame, type Source } from './engine';
const KEY = 'servitium.ludus.freecell.v1';
const load = (): FreeCellGame | null => { try { const value = JSON.parse(localStorage.getItem(KEY) ?? 'null'); return value?.version === 1 ? value : null; } catch { return null; } };
const cardName = (card: { rank:number; suit:keyof typeof suitMark }) => `${rankLabel(card.rank)} of ${card.suit}`;
export default function FreeCell({ onBack }: { onBack: () => void }) {
  const [game, setGame] = useState<FreeCellGame>(() => load() ?? newGame(String(Date.now()))); const [selected, setSelected] = useState<Source | null>(null); const [message, setMessage] = useState(''); const [help, setHelp] = useState(false);
  useEffect(() => { localStorage.setItem(KEY, JSON.stringify(game)); }, [game]);
  useEffect(() => { if (won(game)) return; const id=setInterval(()=>setGame((value)=>({...value,elapsedMs:value.elapsedMs+1000})),1000); return()=>clearInterval(id); }, [won(game)]);
  const chooseSource = (source: Source) => { setSelected(source); setMessage('Card selected. Choose a destination.'); };
  const place = (destination: Destination) => { if (!selected) return; const next=move(game,selected,destination); if (!next) { setMessage('That move is not allowed.'); return; } setGame(next); setSelected(null); setMessage(won(next)?'FreeCell solved!':'Card moved.'); };
  const fresh = () => { if (game.moves && !confirm('Start a new deal? Current progress will be replaced.')) return; setGame(newGame(crypto.randomUUID())); setSelected(null); };
  const restart = () => { if (game.moves && !confirm('Restart this exact deal?')) return; setGame(newGame(game.deal)); setSelected(null); };
  return <main className="freecell-page"><header className="freecell-bar"><button className="text-button" onClick={onBack}>← Ludus</button><div><b>FreeCell</b><small>Deal {game.deal.slice(0,8)} · {game.moves} moves · {Math.floor(game.elapsedMs/60000)}:{String(Math.floor(game.elapsedMs/1000)%60).padStart(2,'0')}</small></div><nav><button onClick={()=>setGame(undo(game))} disabled={!game.history.length}>↶ Undo</button><button onClick={restart}>↺ Restart</button><button onClick={()=>setHelp(!help)}>?</button><button onClick={fresh}>＋ New</button><FullscreenButton iconOnly /></nav></header>
    {help&&<section className="freecell-help"><b>Build foundations Ace to King by suit.</b> Cascades descend in alternating colours. Use the four free cells and empty columns to rearrange cards. Select a card or ordered run, then select its destination.</section>}
    <section className="freecell-top" aria-label="Free cells and foundations"><div className="freecell-spots">{game.cells.map((card,index)=><button key={index} className="card-slot" aria-label={card?`Free cell ${index+1}, ${cardName(card)}`:`Empty free cell ${index+1}`} onClick={()=>card?chooseSource({kind:'cell',index}):place({kind:'cell',index})}>{card&&<CardFace card={card}/>}</button>)}</div><div className="freecell-spots">{SUITS.map((suit)=><button key={suit} className="card-slot foundation" aria-label={`${suit} foundation, ${game.foundations[suit].length?rankLabel(game.foundations[suit].length):'empty'}`} onClick={()=>place({kind:'foundation',suit})}>{game.foundations[suit].length?<CardFace card={game.foundations[suit].at(-1)!}/>:suitMark[suit]}</button>)}</div></section>
    <section className="cascades" aria-label="FreeCell tableau">{game.cascades.map((column,index)=><div className="cascade" key={index}><button className="cascade-target" aria-label={`Cascade ${index+1}${column.length?', destination':' empty'}`} onClick={()=>place({kind:'cascade',index})}/>{column.map((card,cardIndex)=><button key={card.id} className={`playing-card ${selected?.kind==='cascade'&&selected.index===index&&cardIndex>=selected.cardIndex?'selected':''}`} style={{top:`${cardIndex*clampOffset(column.length)}px`}} aria-label={`${cardName(card)}, cascade ${index+1}`} onClick={(event)=>{event.stopPropagation();if(selected)place({kind:'cascade',index});else chooseSource({kind:'cascade',index,cardIndex});}}><CardFace card={card}/></button>)}</div>)}</section>
    <div className="sr-only" aria-live="polite">{message}</div>{won(game)&&<div className="freecell-win"><h1>Deal solved</h1><p>{game.moves} moves</p><button className="primary" onClick={fresh}>New deal</button></div>}
  </main>;
}
const clampOffset=(length:number)=>Math.max(22,Math.min(34,360/Math.max(1,length)));
function CardFace({card}:{card:{rank:number;suit:keyof typeof suitMark;color:'red'|'black'}}){return <span className={card.color}><b>{rankLabel(card.rank)}</b><i>{suitMark[card.suit]}</i></span>;}
